name: CI/CD

env:
  COMMIT-ID: ${{ github.sha }}

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  build:
    name: Build Docker Image and Push to Digital Ocean Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Digital Ocean Containter Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          logout: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.digitalocean.com/diamond-shop-api:$COMMIT-ID

  deploy:
    name: Deploy to Digital Ocean Droplet
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@
        with:
          host: ${{ secrets.DIGITALOCEAN_DROPLET_HOST }}
          username: ${{ secrets.DIGITALOCEAN_DROPLET_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_DROPLET_SSH_PRIVATE_KEY }}
          script: |
            docker pull registry.digitalocean.com/diamond-shop-api:$COMMIT-ID
            docker stop diamond-shop-api || true
            docker rm diamond-shop-api || true
            docker run -d -p 8091:8091 --name diamond-shop-api registry.digitalocean.com/diamond-shop-api:$COMMIT-ID
